package com.nazarko.rateitspring.models.enums;

public enum BookGenre {
    BUSINESS, CLASSICS, COMICS, FANTASY, FICTION, GRAPHIC_NOVELS, HISTORICAL_FICTION, HISTORY,
    HORROR, HUMOR_AND_COMEDY, MYSTERY, PHILOSOPHY, PSYCHOLOGY , SCIENCE, SCIENCE_FICTION,
    THRILLER, TRAVEL, ART, BIOGRAPHY, CHICK_LIT, FOR_CHILDREN, CHRISTIAN, CONTEMPORARY,
    COOKBOOKS, CRIME, EBOOKS, GAY_AND_LESBIAN, MANGA, MEMOIR, MUSIC, NONFICTION, PARANORMAL,
    POETRY, RELIGION, ROMANCE, SELF_HELP, SUSPENSE, SPIRITUALITY, SPORTS, YOUNG_ADULT
}
