package com.nazarko.rateitspring.models.enums;

public enum GameGenre {
    ACTION, PLATFORM, SHOOTER, FIGHTING, BEAT_EM_UP, STEALTH, SURVIVAL, RHYTHM, BATTLE_ROYALE, ACTION_ADVENTURE, SURVIVAL_HORROR,
    METDROIDVANIA, ADVENTURE, INTERACTIVE_MOVIE, PUZZLE, CODING, REAL_TIME, RPG, MMORPG, ROGUELIKE, TACTICAL, SANDBOX, FPS,
    SIMULATION, STRATEGY, MOBA, RTS, RTT, RACING, SPORTS, COMPETITIVE, MMO, BOARD, CASUAL, HORROR, PROGRAMMING, PARTY, LOGIC,
    IDLE, TRIVIA, ESPORTS, EDUCATIONAL, CREATIVE, OPEN_WORLD, CO_OP, MULTIPLAYER, AAA, INDIE, TEAM_BASED, SINGLEPLAYER
}
