package com.nazarko.rateitspring.models.enums;

public enum MovieTVGenre {
    ACTION, ADVENTURE, ANIMATION, ANIME, BIOGRAPHY, COMEDY, CRIME, DOCUMENTARY, DRAMA, FAMILY,
    FANTASY, GAME_SHOW, HISTORY, HORROR, MUSIC, MUSICAL, MYSTERY, NOIR, NEWS, REALITY_TV, ROMANCE,
    SCI_FI, SHORT, SPORT, TALK_SHOW, THRILLER, WAR, WESTERN
}
